experiment_name: RandomForestClassifier

data:
  csv_path: data/WA_Fn-UseC_-Telco-Customer-Churn.csv
  target_column: Churn

model:
  sklearn_class_path: "sklearn.ensemble.RandomForestClassifier"
  sklearn_class_params:
    n_estimators: 100
    random_state: 42